# Generated by Django 3.2.5 on 2021-07-23 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20210720_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('totalpay', models.IntegerField(verbose_name='総差枚数')),
            ],
            options={
                'verbose_name': '差枚数',
                'verbose_name_plural': '差枚数',
                'db_table': 'totalpay',
            },
        ),
        migrations.AlterField(
            model_name='slotdata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
