# Generated by Django 3.2.5 on 2021-07-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20210723_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalpay',
            name='store_name',
            field=models.CharField(default='aaa', max_length=100, verbose_name='店舗名'),
        ),
        migrations.AlterField(
            model_name='totalpay',
            name='totalpay',
            field=models.IntegerField(default=111, verbose_name='総差枚数'),
        ),
    ]
